### ISSUE TITLE
fatal error: 'linux/if.h' file not found

### ISSUE THREAD

**Issue by luckypoem** [jakkarth/icmptx#6]
yudeMacBook-Air:icmptx-0.01 brite$ ls
Makefile	driver.h	it.c		llist.h		vtun.h
README		icmptx.c	lib.h		tun_dev.c
yudeMacBook-Air:icmptx-0.01 brite$ make
gcc -g -c it.c
gcc -g -c icmptx.c
gcc -g -c tun_dev.c
tun_dev.c:35:10: fatal error: 'linux/if.h' file not found
#include <linux/if.h>
         ^
1 error generated.
make: *** [tun_dev.o] Error 1
yudeMacBook-Air:icmptx-0.01 brite$

how to fix it?

**Comment by jakkarth** [comment]
Thanks for the report. Unfortunately, icmptx does not support OSX at this time. It's a linux tool. I do not have the expertise or an OSX computer to test on, so I cannot port it there. Pull requests are accepted if you want to give it a try :)

**Comment by jakkarth** [comment]
Closed due to inactivity.
